site_name: МШИ - NoTryCatch
theme:
    name: mkdocs
    custom_dir: custom_theme/
extra_css: [extra.css]
nav:
    - Главная: index.md
    - Руководство: manual.md
    - Техническая документация: tech.md