name: Deploy Docs

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Docker CI Docs]
    types: [completed]
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Run Docker SSH
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: 22
              script: |
                docker stop docs && docker rm docs
                docker rmi swamp1820/lct2023-docs
                docker pull swamp1820/lct2023-docs:latest
                docker run --name docs -d --restart always -p 8082:80 \
                swamp1820/lct2023-docs 