name: Docker CI PDFJS

on:
  push:
    branches: [master]
    paths:
      - 'pdfjs/**'
jobs:

  build_and_push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the PDFJS Docker image
      run: docker build . --file ./pdfjs/Dockerfile --tag ${{secrets.DOCKER_USER}}/lct2023-pdf:latest
      
    - name: Docker push PDFJS image
      run: docker push ${{secrets.DOCKER_USER}}/lct2023-pdf