name: Deploy CMS

on:
    workflow_dispatch
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Run Docker SSH
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: 22
              script: |
                docker stop cms && docker rm cms
                docker rmi swamp1820/lct2023-cms
                docker pull swamp1820/lct2023-cms:latest
                docker run --name cms -d --restart always -p 80:1337 \
                -e "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" \
                -e "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" \
                -e "APP_KEYS=${{ secrets.APP_KEYS }}" \
                -e "DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}" \
                -e "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" \
                -e "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
                -e "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" \
                -e "DATABASE_PORT=5432" \
                -e "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" \
                -e "FORCE_MIGRATION=false" \
                -e "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
                -e "SMTP_HOST=smtp.mail.ru" \
                -e "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" \
                -e "SMTP_PORT=465" \
                -e "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" \
                swamp1820/lct2023-cms 