name: MkDocs

on:
  push:
    # branches: [master]
    # paths:
    #   - 'docs/**'
jobs:

  build_and_push:
    
    runs-on: python

    steps:
    - uses: actions/checkout@v2

    - name: install mkdocs
      run: pip install mkdocs

    - name: Deploy to Github Pages
      working-directory: docs
      run: mkdocs gh-deploy
    