name: MkDocs

on:
  push:
    # branches: [master]
    # paths:
    #   - 'docs/**'
jobs:

  build_and_push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: install mkdocs
      run: pip install mkdocs

    - name: Deploy to Github Pages
      working-directory: docs
      run: mkdocs gh-deploy
    